# Generated by Django 4.1.5 on 2023-01-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_demand_models_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geography_models_salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=20, verbose_name='Город')),
                ('salary_level', models.IntegerField(max_length=10, verbose_name='Уровень зарплат')),
            ],
            options={
                'verbose_name': 'Георграфия - зарплата',
                'verbose_name_plural': 'Георграфия - зарплата',
            },
        ),
        migrations.CreateModel(
            name='Geography_models_vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=20, verbose_name='Город')),
                ('vacancy_rate', models.CharField(max_length=7, verbose_name='Доля вакансий')),
            ],
            options={
                'verbose_name': 'Георграфия - вакансии',
                'verbose_name_plural': 'Георграфия - вакансии',
            },
        ),
    ]
